services:
  mc-server:
    build: .
    container_name: mc-server
    restart: unless-stopped
    ports:
      - "${MC_PORT:-8888}:25565"
    environment:
      JAVA_MIN_MEM: ${MC_MEMORY_MIN:-1G}
      JAVA_MAX_MEM: ${MC_MEMORY_MAX:-2G}
    volumes:
      - mc_data:/data

volumes:
  mc_data:
